#!/usr/bin/env python3
"""Generate src/lisp_prelude_generated.inc from lisp/prelude.el.

Sub-plan 01A
(doc/plans/2026-08-03-elisp-subset-and-fe-evaluator-subplans/01a-prelude-extraction.md):
kg's Lisp prelude used to live as 54 definitions inside three C string
literals in src/lisp_prelude.c, split at 4095 bytes only because that is
what a C string literal guarantees.  lisp/prelude.el (named lisp/prelude.fe
until sub-plan 02D's dialect cutover) is now the canonical, human-edited
source; this script turns its exact bytes into a checked-in C translation
unit so an ordinary build needs no Python.

Deliberately dumb: it does not parse Lisp, reformat whitespace, sort, or
dedupe anything.  It reads the input file as raw bytes and writes them
out as a `static const unsigned char` array in source order, unchanged --
reordering or deduplicating would silently break the prelude, whose
ordering is load-bearing (see lisp/prelude.el's own header comment).

The emitted array carries its own length as `sizeof(...)`, counted from
the initializer list, not from a trailing NUL the generator does not
add.  kg's evaluate_prelude() passes that length straight to
FeEvaluateStringWithOptions(), which already takes an explicit length, so
nothing here or there depends on NUL termination.

Usage:
    embed_lisp.py <input.el> <output.inc>

`make lisp-prelude-generate` runs this to refresh the checked-in file;
`make lisp-prelude-check` (part of `make check`) runs it again into a
temporary file and fails if that differs from what is checked in --
regenerating must be a no-op on a clean tree.
"""

from __future__ import annotations

import sys
from pathlib import Path

ARRAY_NAME = "lisp_prelude_generated"
BYTES_PER_LINE = 12

HEADER = """/* Generated by utils/embed_lisp.py from lisp/prelude.el.  DO NOT EDIT.
 *
 * Edit lisp/prelude.el and run `make lisp-prelude-generate` to refresh
 * this file; `make lisp-prelude-check` (part of `make check`) fails the
 * build if the two have drifted apart.
 *
 * A byte array plus an explicit length, not a NUL-terminated string:
 * evaluate_prelude() (src/lisp_prelude.c) passes the paired _len
 * constant straight to FeEvaluateStringWithOptions(), which already
 * takes a length, so this file makes no claim about what byte, if
 * any, follows the array.
 * The bytes are lisp/prelude.el's, unchanged and in source order --
 * reordering or deduplicating them would break the prelude, whose
 * ordering is load-bearing. */

static const unsigned char {name}[] = {{
{body}
}};

static const size_t {name}_len = sizeof({name});
"""


def render(source: bytes) -> str:
	rows = []
	for offset in range(0, len(source), BYTES_PER_LINE):
		chunk = source[offset:offset + BYTES_PER_LINE]
		rows.append("\t" + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
	body = "\n".join(rows)
	return HEADER.format(name=ARRAY_NAME, body=body)


def main(argv: list[str]) -> int:
	if len(argv) != 3:
		print(f"usage: {argv[0]} <lisp/prelude.el> <output.inc>",
		      file=sys.stderr)
		return 2
	input_path = Path(argv[1])
	output_path = Path(argv[2])
	source = input_path.read_bytes()
	if len(source) == 0:
		print(f"embed_lisp.py: {input_path} is empty", file=sys.stderr)
		return 1
	output_path.write_text(render(source), encoding="utf-8")
	print(f"embed_lisp.py: wrote {output_path} ({len(source)} bytes from "
	      f"{input_path})")
	return 0


if __name__ == "__main__":
	sys.exit(main(sys.argv))
