#ifndef KG_SYNTAX_H
#define KG_SYNTAX_H

/* Syntax highlighting: what a row's hl[] bytes mean, what a mode is, and
 * how the editor asks for a row to be re-coloured.  Every offset into
 * row->hl is a byte offset into row->render -- see doc/coordinates.md.
 *
 * Backend-neutral by construction: nothing here says how a mode is
 * fontified.  That is src/syntax_backend.h's private contract, implemented
 * today by src/syntax_legacy.c's bespoke scanners. */

#include <stddef.h> /* size_t, for the byte positions in kg_syntax_edit */

/* Forward declarations; the full types are defined in def.h, which
 * syntax.c includes to reach their members.  Rows are spelled with the
 * struct tag rather than def.h's `erow` typedef so this header needs
 * nothing from def.h at all. */
struct editor_buffer;
struct erow;

/* Whatever the compiled-in backend keeps about one buffer's *whole* text:
 * a parser and the tree it produced, for a backend that parses; nothing at
 * all, for the legacy row scanners, which derive every row from the row
 * above it and so keep no state a buffer has to own.
 *
 * Declared here and defined by the backend, never by def.h -- a buffer
 * carries a `struct kg_syntax_state *` (def.h) without any editor module,
 * or any standalone-header check, meeting the backend's own headers.
 *
 * One buffer owns at most one.  It is prepared against a complete document
 * (syntax_prepare_rows()), installed on the buffer that keeps that document
 * (syntax_state_adopt()), and released the moment the buffer stops
 * describing that document (syntax_state_release()). */
struct kg_syntax_state;

/* Syntax highlight types */
#define HL_NORMAL 0
#define HL_NONPRINT 1
#define HL_COMMENT 2 /* Single line comment. */
#define HL_MLCOMMENT 3 /* Multi-line comment. */
#define HL_KEYWORD1 4
#define HL_KEYWORD2 5
#define HL_STRING 6
#define HL_NUMBER 7
#define HL_MATCH 8 /* Search match. */
#define HL_WARNING 9 /* Overlong commit subject, etc. */
#define HL_PAREN_MATCH 10 /* show-paren: the pair agrees. */
#define HL_PAREN_MISMATCH 11 /* show-paren: it does not, or has no partner. */
#define HL_BREAKPOINT 12 /* The debugger: a verified breakpoint. */
#define HL_BREAKPOINT_PENDING 13 /* ... one no adapter has verified. */
#define HL_DEBUG_CURRENT 14 /* ... the line the program is stopped on. */

/* Stable identity of an editor mode, independent of how -- or whether --
 * it highlights.  Every struct editor_syntax carries one: the HLDB
 * registry entries in syntax.c and the synthetic records bufmgr.c and
 * dired.c own, so no non-highlighting behavior has to recognize a mode by
 * its highlighter function pointer.  KG_MODE_TEXT is first, and is the
 * mode a zero-initialized record names. */
enum kg_mode_id {
	KG_MODE_TEXT = 0,
	/* The HLDB registry, in table order. */
	KG_MODE_C,
	KG_MODE_PYTHON,
	KG_MODE_SHELL,
	KG_MODE_JAVASCRIPT,
	KG_MODE_RUST,
	KG_MODE_GO,
	KG_MODE_JAVA,
	KG_MODE_TYPESCRIPT,
	KG_MODE_CSHARP,
	KG_MODE_PHP,
	KG_MODE_RUBY,
	KG_MODE_SWIFT,
	KG_MODE_SQL,
	KG_MODE_DART,
	KG_MODE_HTML,
	KG_MODE_REACT,
	KG_MODE_VUE,
	KG_MODE_ANGULAR,
	KG_MODE_SVELTE,
	KG_MODE_MAKEFILE,
	KG_MODE_MARKDOWN,
	KG_MODE_LISP,
	KG_MODE_GIT_COMMIT,
	KG_MODE_GIT_REBASE,
	KG_MODE_YAML,
	/* Synthetic modes, deliberately outside HLDB: never selected by a
	 * filename, so syntax_find_by_mode() does not resolve them. */
	KG_MODE_IBUFFER,
	KG_MODE_COMPILATION,
	KG_MODE_LISP_INTERACTION,
	KG_MODE_DIRED,
	/* One past the last mode, and the reason it exists: the identities
	 * above are dense from zero, so a table keyed by mode can be a flat
	 * array indexed by the id rather than a search.  Not a mode; nothing
	 * ever carries it. */
	KG_MODE_COUNT,
};

/* What a buffer's mode is.  Identity, display name, how a file name
 * selects it, and the one piece of comment syntax that is a *command*
 * rather than a colour.  Everything a particular highlighting backend
 * needs to know about a mode -- keyword lists, multi-line comment
 * delimiters, per-scanner flags -- is that backend's own table, keyed by
 * `id`; it is deliberately not visible here, where mode semantics could
 * come to depend on it. */
struct editor_syntax {
	enum kg_mode_id id;
	char *name; /* Display name shown in mode line, e.g. "C", "Python" */
	char **filematch;
	/* comment-dwim (src/word.c) inserts this, so it is command
	 * semantics and outlives any highlighting backend. */
	char singleline_comment_start[5];
	/* A highlighter the mode owns outright, bypassing the backend
	 * entirely; NULL for every registry mode, which is what makes the
	 * backend swappable.  Dired's listing is the one real user: its
	 * colours are generated by kg, not scanned from a file.  The buffer
	 * is passed because a multi-line construct's state comes from the
	 * row above, which is only reachable through the buffer that owns
	 * it. */
	void (*highlight)(struct editor_buffer *b, struct erow *row);
};

/* A position in the text, as the syntax layer is told about one: a row
 * index and a byte offset into that row's `chars` -- doc/coordinates.md's
 * **chars** space, not render bytes and not display columns.  A TAB is one
 * column here however wide it is drawn, which is the coordinate system an
 * incremental parser wants (tree-sitter's TSPoint.column is the same
 * thing: source bytes from the start of the line).  No render or tab
 * conversion belongs anywhere near these numbers. */
struct kg_text_point {
	int row;
	int column;
};

/* One completed edit, described for whoever keeps state derived from the
 * whole text.  The three byte positions are doc/coordinates.md's **buffer
 * byte** space -- the flattened buffer, one '\n' between rows -- and are
 * exactly kg_buffer_replace()'s begin_byte/end_byte and the end of what it
 * put there.  The three points are the same three positions in row/column
 * form: `old_end_*` describes the text as it was *before* the edit and
 * `start_*`/`new_end_*` the text as it is *after* it, which is why an
 * insertion has old_end == start and a deletion new_end == start.
 *
 * The shape is deliberate: it is field for field tree-sitter's
 * TSInputEdit (doc/plans/kg-tree-sitter-plan.md, Phase 3), so a backend
 * that reparses incrementally can pass one straight through. */
struct kg_syntax_edit {
	size_t start_byte;
	size_t old_end_byte;
	size_t new_end_byte;
	struct kg_text_point start_point;
	struct kg_text_point old_end_point;
	struct kg_text_point new_end_point;
};

/* syntax.c */
void editor_update_syntax(struct editor_buffer *b, struct erow *row);
void syntax_after_edit(
    struct editor_buffer *b, const struct kg_syntax_edit *edit);
void syntax_rebuild(struct editor_buffer *b);
void editor_rehighlight_from(struct editor_buffer *b, int start_idx);
struct editor_syntax *syntax_find_by_name(const char *name);
struct editor_syntax *syntax_find_by_mode(enum kg_mode_id id);
void editor_set_syntax(struct editor_buffer *b, struct editor_syntax *syntax);
void editor_rehighlight_all(struct editor_buffer *b);
int editor_syntax_to_color(int hl);
void editor_select_syntax_highlight(struct editor_buffer *b, char *filename);

/* ---- Git mode semantics -------------------------------------------------
 *
 * What a commit message or a rebase todo *means*, as opposed to what
 * colour it is: the C-c action keys and the diagnostics (src/gitdiag.h)
 * read these, so they belong to the facade and stay available whatever
 * backend (if any) is highlighting.
 *
 * Each predicate comes in two spellings.  The zero-argument one asks
 * about the current buffer, which is what a command handler wants; the
 * `_buffer` one asks about a named buffer, which is what a module handed
 * a `struct editor_buffer *` -- a repaint walking the windows, say --
 * needs, since the buffer it was given is not always the selected one. */
[[nodiscard]] int syntax_is_git_commit(void);
[[nodiscard]] int syntax_buffer_is_git_commit(const struct editor_buffer *b);
[[nodiscard]] int syntax_git_commit_subject(void);
[[nodiscard]] int syntax_buffer_git_commit_subject(
    const struct editor_buffer *b);
[[nodiscard]] int syntax_is_git_rebase(void);
[[nodiscard]] int syntax_buffer_is_git_rebase(const struct editor_buffer *b);
int syntax_git_rebase_pick_span(
    const char *line, int len, int *start, int *wlen);
int syntax_git_rebase_flags_end(const char *line, int len, int from);

/* Index of the first byte at or after `from` that is not a space or tab. */
int syntax_git_rebase_skip_ws(const char *line, int len, int from);

/* Index just past the word starting at `from`. */
int syntax_git_rebase_skip_word(const char *line, int len, int from);

/* The canonical name of the git-rebase-todo action spelled by
 * word[0..len) -- long or single-letter abbreviation -- or NULL when it
 * names none.  On a hit *takes_commit says whether a commit hash follows
 * the action word. */
const char *syntax_git_rebase_action_name(
    const char *word, int len, int *takes_commit);

/* ---- Per-buffer backend state ------------------------------------------
 *
 * Prepare a backend's whole-buffer state against a staged, unpublished row
 * array -- edit.h's row builder, already rendered by
 * kg_row_builder_render() -- and colour every one of those rows on the way.
 * `syntax` is the mode the finished buffer will be in; it is passed rather
 * than read off a buffer because the rows belong to no buffer yet.
 * `filename` is the file those rows came from, or NULL for rows kg
 * generated (a dired listing, an ibuffer).  It is not how the mode is
 * chosen -- the caller has already done that -- but a mode can be spelled
 * by more than one grammar, and which one is a question only the name
 * answers: kg's TypeScript mode covers both .ts and .tsx, and the two are
 * different tree-sitter grammars.  Without it a .tsx file would be painted
 * on load by the .ts grammar and only corrected by the first edit.
 *
 * This is the load path's whole highlighting pass, and the reason it is one
 * call over the complete document rather than one call per row: a backend
 * that parses cannot see a row at a time.  Returns the prepared state, which
 * the caller then owns and must either hand to a buffer
 * (syntax_state_adopt()) or throw away (syntax_state_discard()); a backend
 * that keeps no state returns NULL having still done the colouring, so NULL
 * is not a failure.  Failure is `*ok` set to 0, which is the editor running
 * out of memory mid-pass, and comes with a NULL state. */
struct kg_syntax_state *syntax_prepare_rows(struct erow *rows, int numrows,
    struct editor_syntax *syntax, char *filename, int *ok);

/* Install `st` as `b`'s state, releasing whatever `b` held: the ownership
 * transfer at the end of a staged load. */
void syntax_state_adopt(struct editor_buffer *b, struct kg_syntax_state *st);

/* Drop `b`'s state and leave the field NULL.  Every path on which a buffer
 * stops describing the text its state was prepared against calls this:
 * buffer kill and slot reuse (src/bufmgr.c), session teardown
 * (editor_cleanup()), a real mode change (editor_set_syntax()) and a broad
 * replacement of a buffer's rows (kg_buffer_adopt_rows()).  Idempotent, and
 * safe on a buffer that never had one. */
void syntax_state_release(struct editor_buffer *b);

/* Free a prepared state no buffer ever took: an abandoned load.  NULL is a
 * state like any other and is accepted. */
void syntax_state_discard(struct kg_syntax_state *st);

#endif /* KG_SYNTAX_H */
